[general]
live_config_reload = true
import             = ["./alacritty.local.toml"]

[env]
TERM = "xterm-256color"

[cursor]
style = { blinking = "Never" }

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
]

[window]
option_as_alt   = "Both"
dynamic_padding = true
